CREATE TABLE choir_music (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    composer TEXT,
    arranger TEXT,
    title TEXT NOT NULL,
    voicing TEXT,
    number_copies INTEGER,
    lang TEXT,
    instrumentation TEXT,
    notes TEXT
);